### ISSUE TITLE
Command Line Relative Directories

### ISSUE THREAD

**Issue by Meerkov** [m35/jpsxdec#41]
Environment
-------------

jPSXdec version: 1.00 (whatever the latest is).

Operating system: Windows

Java runtime environment : 

 Description 
-------------
C:\Users\admin\Desktop\jpsxdec>"../jpsxdec/jpsxdec.exe" -f "../sibling/Isos/(USA).bin" -x "../sibling/Indexes/(USA).idx"

This works.

C:\Users\admin\Desktop\sibling>"../jpsxdec/jpsxdec.exe" -f "../sibling/Isos/(USA).bin" -x "../sibling/Indexes/(USA).idx"

This doesn't work (and provides no debug output or anything).

**Comment by m35** [comment]
It seems the .exe fails silently when it's executed from a directory without `jpsxdec.jar`. That is odd.

But I don't recommend using the .exe from the command-line. Due to the way Windows works, you won't see any console output at all. It's best to execute the .jar directly with Java.
```
java -jar "../jpsxdec/jpsxdec.jar" -f "../sibling/Isos/(USA).bin" -x "../sibling/Indexes/(USA).idx"
```
In this way it will work when running from any directory.

**Comment by Meerkov** [comment]
Thanks, I'll try that

**Comment by m35** [comment]
Hey thanks for continuing to report your findings! The next release has been greatly delayed due to daily life and feature creep, but still progressing.

I'd like to keep this bug open since I want to check if there's a way to at least display a message when this happens.

**Comment by Meerkov** [comment]
Executing the .exe from a different Working Directory in version 2 no longer fails silently I think this is fixed
