### ISSUE TITLE
Convert audio in 44100 Hz

### ISSUE THREAD

**Issue by leop2p** [m35/jpsxdec#93]
Hi there!!!

Could you please make a possibility to export audio in 44100 Hz like PSMPlay does without loss of quality and with no speed changes.

Thank you!!!

**Comment by m35** [comment]
Thank you for the suggestion. For a little background, the PlayStation 1 only supported audio at 18900 Hz and 37800 Hz. Unfortunately changing the audio sample-rate to 44100 Hz isn't a lossless operation. Data will be lost in the process. We don't know what algorithm PSMPlay uses since it's not open source.

There are other widely used and proven tools that will undoubtedly give you better results than anything I come up with. So adding half-baked audio resampling in jPSXdec would do more harm than good. I know it's not as convenient, but please look for other tools that can give you the best results will the least amount of quality loss.

**Comment by leop2p** [comment]
OK, thank you!
